### ISSUE TITLE
Support for SASS maps

### ISSUE THREAD

**Issue by Richacinas** [kchmck/babel-plugin-sass-vars#1]
Is there any thoughts or orientation available about how to make this plugin work with the Maps that it finds in the file?

Right now, a Map like this:

```
$breakpoints: (
  xs: $xs,
  sm: $sm,
  md: $md,
  lg: $lg,
  xl: $xl
);
```

Is exported like this:

`"breakpoints": "(xs: 450px, sm: 768px, md: 992px, lg: 1024px, xl: 1200px)"`

**Comment by kchmck** [comment]
I'm tempted to leave interpreting of these up to the user for each specific case, because I feel like trying to convert them to JS objects in the general case could get tricky.

Once you start getting into degenerate cases like
```scss
$map: (                                                                                    
  nested: (                                                                                
    key1: 123,                                                                             
    key2: 456,                                                                             
  ),                                                                                       
  abc: (1, 2, (key: 123)),                                                                 
  def: (),                                                                                 
  ghi: 123,                                                                                
);        
```                  
that result in `"(nested: (key1: 123, key2: 456), abc: 1, 2, (key: 123), def: , ghi: 123)"`, it seems like you'd need a fairly involved parser to pull out the keys/values and recognize nested lists/maps. Also deciding how to handle maps embedded in lists, which we also don't interpret at this time.

But I might be missing something. Maybe gonzales-pe is able to parse this stuff and it's a matter of running a second pass with it on these expressions and interpreting its parse tree? I'd be open to checking out a pull request in any case.

**Comment by Richacinas** [comment]
Good thoughts.

Yeah, it smells like a proper recursion would work. I just never developed or worked on a Babel plugin.
